### ISSUE TITLE
Crash on game load related to config not loaded yet

### ISSUE THREAD

**Issue by Reyzerbit** [Keksuccino/Drippy-Loading-Screen#17]
**Describe the bug**
For whatever reason, the mods ArmorPlus and UpgradedNetherite cause the game to crash on startup when included in modpack with DrippyLoadingScreens

**To Reproduce**
1. Install DrippyLoadingScreen
2. Install ArmorPlus mod [here](https://www.curseforge.com/minecraft/mc-mods/armorplus) or UpgradedNetherite mod [here](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)
3. Launch Game
4. Crash

**Expected behavior**
Pretty self explanatory... just don't crash

**Crash Log**
https://pastebin.com/QAcrm8ni

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - Drippy Loading Screen Version 1.6.1
 - Forge/Fabric Version 40.1.20
 - Minecraft Version 1.18.2
 - Active Mods UpgradedNetherite and/or ArmorPlus

**Comment by PantsWP** [comment]
I don't have either of those mods installed but since updating to 1.6.1, I also receive the same crash. I think it might be something to do with the mod failing to recognise a config file exists.

**Comment by Keksuccino** [comment]
Fixed in Drippy Loading Screen v1.6.2! Thank you for your report! :)

**Comment by Reyzerbit** [comment]
Issue continues to exist... I think somehow the issue is still incompatibility.

**Comment by Keksuccino** [comment]
> Issue continues to exist... I think somehow the issue is still incompatibility.

Please send me your `latest.log` file after the crash happened, thank you.

**Comment by Keksuccino** [comment]
Should hopefully be fixed now. If this still happens, please comment here.
